'use client'

import { useState, type CSSProperties } from 'react'
import { ArrowLeft, Calendar, Edit3, Plus, RotateCcw, Trash2, WalletCards } from 'lucide-react'
import { Button, Card } from '@/components/ui'
import { formatCurrency } from '@/lib/fx'
import type { AssetActivity, AssetActivityKind, AssetDetail } from '@/lib/assets/types'
import type { AssetActivityInput } from '@/lib/assets/activity'

const label: CSSProperties = { display: 'block', marginBottom: 6, fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '.14em', textTransform: 'uppercase', color: 'var(--fg3)' }
const control: CSSProperties = { width: '100%', height: 42, borderRadius: 10, padding: '0 12px', background: 'rgba(255,255,255,.04)', border: '1px solid var(--card-border)', color: 'var(--fg)', fontSize: 13, outline: 'none', colorScheme: 'dark' }

type AccountOption = { id: string; name: string; type: string; currency?: string }
type CategoryOption = { id: string; name: string; type: 'income' | 'expense' }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return <><div className="fixed inset-0 z-40 bg-black/65 backdrop-blur-sm" onClick={onClose}/><div role="dialog" aria-modal="true" className="fixed inset-x-4 top-1/2 z-50 mx-auto max-w-lg -translate-y-1/2 rounded-[18px] border border-card bg-bg2 p-5 shadow-2xl md:p-6"><h2 className="font-display text-lg font-semibold">{title}</h2>{children}</div></>
}

function ValuationModal({ asset, onClose, onSave }: { asset: AssetDetail; onClose: () => void; onSave: (input: { totalValue: number; valuedOn: string; source?: string; notes?: string }) => Promise<void> }) {
  const [value, setValue] = useState(asset.totalMarketValue)
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10))
  const [source, setSource] = useState('Manual estimate')
  const [notes, setNotes] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await onSave({ totalValue: Number(value), valuedOn: date, source, notes }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save valuation') } finally { setSaving(false) } }
  return <Modal title="Record valuation" onClose={onClose}><form onSubmit={submit} className="mt-5 space-y-4"><div><label style={label}>Total market value · {asset.currency}</label><input type="number" min="0" step="any" required value={value} onChange={(e) => setValue(Number(e.target.value))} style={control}/></div><div><label style={label}>Valuation date</label><input type="date" required value={date} onChange={(e) => setDate(e.target.value)} style={control}/></div><div><label style={label}>Source</label><input value={source} onChange={(e) => setSource(e.target.value)} style={control}/></div><div><label style={label}>Notes</label><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} style={{ ...control, height: 'auto', paddingTop: 10 }}/></div>{error && <p className="text-sm text-bad">{error}</p>}<div className="flex justify-end gap-3 pt-2"><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="primary" disabled={saving}>{saving ? 'Saving…' : 'Record value'}</Button></div></form></Modal>
}

const activityLabels: Record<AssetActivityKind, string> = {
  capital_contribution: 'Capital contribution / purchase', capital_distribution: 'Capital distribution / sale', dividend: 'Dividend', interest: 'Interest', rent: 'Rent', fee: 'Fee', tax: 'Tax', insurance: 'Insurance', maintenance: 'Maintenance', other_income: 'Other income', other_expense: 'Other expense',
}

function ActivityModal({ accounts, categories, onClose, onSave }: { accounts: AccountOption[]; categories: CategoryOption[]; onClose: () => void; onSave: (input: AssetActivityInput) => Promise<void> }) {
  const [kind, setKind] = useState<AssetActivityKind>('capital_contribution')
  const [cashAccountId, setCashAccountId] = useState(accounts.find((a) => a.type !== 'investment')?.id || '')
  const [categoryId, setCategoryId] = useState('')
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10))
  const [description, setDescription] = useState('')
  const [amount, setAmount] = useState(0)
  const [error, setError] = useState('')
  const isIncome = ['dividend','interest','rent','other_income'].includes(kind)
  const isCapital = kind.startsWith('capital_')
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); try { await onSave({ activityKind: kind, cashAccountId, categoryId: isCapital ? undefined : categoryId, date, description, amount }); onClose() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save activity') } }
  return <Modal title="Record asset activity" onClose={onClose}><form onSubmit={submit} className="mt-5 space-y-4"><div><label style={label}>Activity</label><select value={kind} onChange={(e) => { setKind(e.target.value as AssetActivityKind); setCategoryId('') }} style={control}>{Object.entries(activityLabels).map(([value, title]) => <option key={value} value={value}>{title}</option>)}</select></div><div><label style={label}>Cash account</label><select required value={cashAccountId} onChange={(e) => setCashAccountId(e.target.value)} style={control}><option value="">Select account</option>{accounts.filter((a) => a.type !== 'investment').map((a) => <option key={a.id} value={a.id}>{a.name} · {a.currency || 'USD'}</option>)}</select></div>{!isCapital && <div><label style={label}>{isIncome ? 'Income' : 'Expense'} category</label><select required value={categoryId} onChange={(e) => setCategoryId(e.target.value)} style={control}><option value="">Select category</option>{categories.filter((category) => category.type === (isIncome ? 'income' : 'expense')).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div>}<div className="grid grid-cols-2 gap-3"><div><label style={label}>Date</label><input type="date" required value={date} onChange={(e) => setDate(e.target.value)} style={control}/></div><div><label style={label}>Amount</label><input type="number" min="0.01" step="any" required value={amount || ''} onChange={(e) => setAmount(Number(e.target.value))} style={control}/></div></div><div><label style={label}>Description</label><input required value={description} onChange={(e) => setDescription(e.target.value)} style={control}/></div>{error && <p className="text-sm text-bad">{error}</p>}<div className="flex justify-end gap-3 pt-2"><Button onClick={onClose}>Cancel</Button><Button type="submit" variant="primary">Record activity</Button></div></form></Modal>
}

function detailRows(asset: AssetDetail): Array<[string, string | number | boolean | undefined]> {
  const details = asset.details
  if (details.category === 'real_estate') return [['Property type', details.propertyType], ['Primary residence', details.primaryResidence ? 'Yes' : 'No'], ['Purchase price', details.purchasePrice != null ? formatCurrency(details.purchasePrice, asset.currency) : undefined], ['Purchase date', details.purchaseDate], ['Street', details.street], ['City', details.city], ['State / province', details.stateProvince], ['Postal code', details.postalCode], ['Country', details.country]]
  if (details.category === 'vehicle') return [['VIN', details.vin], ['Make', details.make], ['Model', details.model], ['Year', details.year], ['Purchase price', details.purchasePrice != null ? formatCurrency(details.purchasePrice, asset.currency) : undefined], ['Purchase date', details.purchaseDate], ['Current mileage', details.currentMileage], ['Mileage as of', details.mileageAsOf]]
  if (details.category === 'private_investment') return [['Investment type', details.investmentType], ['Investment name', details.investmentName], ['Company', details.companyName], ['Company description', details.companyDescription], ['Website', details.website], ['Investment date', details.investmentDate], ['Cost basis', details.costBasis != null ? formatCurrency(details.costBasis, asset.currency) : undefined], ['Shares / units', details.sharesOrUnits], ['Unit label', details.unitLabel]]
  return [['Plan type', details.planType], ['Plan name', details.planName], ['Provider', details.providerName], ['Account / policy', details.accountReferenceLast4 ? `•••• ${details.accountReferenceLast4}` : undefined], ['Start date', details.startDate], ['Contribution', details.contributionAmount != null ? `${formatCurrency(details.contributionAmount, asset.currency)} ${details.contributionFrequency || ''}` : undefined], ['Target retirement', details.targetRetirementDate]]
}

export function AssetDetailView({ asset, activity, accounts, categories, onBack, onEdit, onValuation, onActivity, onArchive, onRestore }: {
  asset: AssetDetail; activity: AssetActivity[]; accounts: AccountOption[]; categories: CategoryOption[]; onBack: () => void; onEdit: () => void
  onValuation: (input: { totalValue: number; valuedOn: string; source?: string; notes?: string }) => Promise<void>
  onActivity: (input: AssetActivityInput) => Promise<void>; onArchive: () => Promise<void>; onRestore: () => Promise<void>
}) {
  const [tab, setTab] = useState<'overview'|'activity'|'valuations'>('overview')
  const [valuationOpen, setValuationOpen] = useState(false)
  const [activityOpen, setActivityOpen] = useState(false)
  const rows = detailRows(asset).filter(([, value]) => value !== undefined && value !== '')
  return <div className="mx-auto max-w-6xl p-4 md:p-6 lg:px-8">
    <button onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-xs text-fg3 hover:text-fg"><ArrowLeft size={15}/> Assets</button>
    <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-accent">{asset.category.replaceAll('_',' ')}</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-tight">{asset.name}</h1><p className="mt-2 text-sm text-fg3">{asset.primaryFact || asset.subtype || 'Complete the profile to add context.'}</p></div><div className="flex flex-wrap gap-2"><Button icon={Edit3} onClick={onEdit}>Edit</Button><Button icon={WalletCards} onClick={() => setActivityOpen(true)}>Activity</Button><Button variant="primary" icon={Plus} onClick={() => setValuationOpen(true)}>Valuation</Button></div></div>
    <div className="mt-7 grid gap-4 md:grid-cols-3"><Card><p className="font-mono text-[9px] uppercase tracking-[.15em] text-fg3">Total market value</p><p className="mt-2 font-display text-2xl font-semibold">{formatCurrency(asset.totalMarketValue, asset.currency)}</p></Card><Card><p className="font-mono text-[9px] uppercase tracking-[.15em] text-fg3">Included value</p><p className="mt-2 font-display text-2xl font-semibold text-accent">{formatCurrency(asset.currentValue, asset.currency)}</p></Card><Card><p className="font-mono text-[9px] uppercase tracking-[.15em] text-fg3">Latest valuation</p><p className="mt-2 font-display text-xl font-semibold">{asset.latestValuationDate || 'Not valued'}</p><p className="mt-1 text-xs text-fg3">{asset.latestValuationSource || 'No source'}</p></Card></div>
    <nav className="mt-8 flex gap-1 border-b border-card" aria-label="Asset views">{(['overview','activity','valuations'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`border-b-2 px-4 py-3 text-sm capitalize ${tab === item ? 'border-accent-solid text-fg' : 'border-transparent text-fg3'}`}>{item}</button>)}</nav>
    <div className="mt-6">
      {tab === 'overview' && <div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><Card><h2 className="font-display text-base font-semibold">Profile</h2><dl className="mt-5 grid gap-x-6 gap-y-5 sm:grid-cols-2">{rows.length ? rows.map(([title, value]) => <div key={title}><dt className="font-mono text-[9px] uppercase tracking-[.13em] text-fg4">{title}</dt><dd className="mt-1.5 text-sm text-fg2">{String(value)}</dd></div>) : <p className="text-sm text-fg3">No typed details yet.</p>}</dl>{asset.notes && <div className="mt-6 border-t border-card pt-5"><p className="font-mono text-[9px] uppercase tracking-[.13em] text-fg4">Notes</p><p className="mt-2 text-sm leading-6 text-fg2">{asset.notes}</p></div>}</Card><Card><h2 className="font-display text-base font-semibold">Ownership</h2><div className="mt-5 space-y-4">{asset.owners.map((owner) => <div key={owner.ownerId}><div className="flex justify-between text-sm"><span className="text-fg2">{owner.ownerName}</span><span className="font-mono">{Number(owner.percentage.toFixed(2))}%</span></div><div className="mt-2 h-1 rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-accent-solid" style={{ width: `${owner.percentage}%` }}/></div><p className="mt-1.5 text-[10px] text-fg4">{owner.includeInNetWorth ? 'Included in net worth' : 'Excluded from net worth'}</p></div>)}</div></Card></div>}
      {tab === 'activity' && <Card pad={0}><div className="flex items-center justify-between border-b border-card p-5"><div><h2 className="font-display text-base font-semibold">Ledger activity</h2><p className="mt-1 text-xs text-fg3">Capital movements affect asset value; income and expenses affect cash.</p></div><Button icon={Plus} onClick={() => setActivityOpen(true)}>Add</Button></div>{activity.length ? <div className="divide-y divide-card">{activity.map((item) => <div key={item.id} className="flex items-center gap-4 p-4 md:px-5"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${item.direction === 'in' ? 'bg-emerald-400/10 text-good' : 'bg-rose-400/10 text-bad'}`}><WalletCards size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm text-fg">{item.description}</p><p className="mt-1 text-[11px] text-fg3">{item.activityKind ? activityLabels[item.activityKind] : 'Unclassified activity'} · {item.date}</p></div><p className={`font-mono text-sm ${item.direction === 'in' ? 'text-good' : 'text-bad'}`}>{item.direction === 'in' ? '+' : '−'}{formatCurrency(item.amount, item.currency)}</p></div>)}</div> : <p className="p-10 text-center text-sm text-fg3">No linked activity yet.</p>}</Card>}
      {tab === 'valuations' && <Card pad={0}><div className="flex items-center justify-between border-b border-card p-5"><div><h2 className="font-display text-base font-semibold">Valuation history</h2><p className="mt-1 text-xs text-fg3">Append-only record; corrections are entered as a newer valuation.</p></div><Button icon={Plus} onClick={() => setValuationOpen(true)}>Add</Button></div><div className="divide-y divide-card">{asset.valuations.map((valuation, index) => <div key={valuation.id} className="grid gap-2 p-4 sm:grid-cols-[120px_1fr_auto] sm:items-center md:px-5"><span className="inline-flex items-center gap-2 font-mono text-xs text-fg3"><Calendar size={13}/>{valuation.valuedOn}</span><div><p className="text-sm text-fg2">{valuation.source || 'No source'}{index === 0 && <span className="ml-2 rounded-full bg-sky-400/10 px-2 py-0.5 text-[10px] text-accent">Current</span>}</p>{valuation.notes && <p className="mt-1 text-xs text-fg4">{valuation.notes}</p>}</div><div className="text-right"><p className="font-mono text-sm text-fg">{formatCurrency(valuation.totalValue, valuation.currency)}</p><p className="mt-1 text-[10px] text-fg4">{Number(valuation.includedOwnershipPercentage.toFixed(2))}% included</p></div></div>)}</div></Card>}
    </div>
    <div className="mt-8 flex justify-end">{asset.deletedAt ? <Button icon={RotateCcw} onClick={() => void onRestore()}>Restore asset</Button> : <Button variant="danger" icon={Trash2} onClick={() => void onArchive()}>Archive asset</Button>}</div>
    {valuationOpen && <ValuationModal asset={asset} onClose={() => setValuationOpen(false)} onSave={onValuation}/>} {activityOpen && <ActivityModal accounts={accounts} categories={categories} onClose={() => setActivityOpen(false)} onSave={onActivity}/>} 
  </div>
}
